language: ruby

rvm:
 - 2.4.1

gemfile:
  - gemfiles/Gemfile-rails-4-0
  - gemfiles/Gemfile-rails-4-1
  - gemfiles/Gemfile-rails-4-2
  - gemfiles/Gemfile-rails-5-0
  - gemfiles/Gemfile-sprockets-2-11
  - gemfiles/Gemfile-sprockets-2-12
  - gemfiles/Gemfile-sprockets-2-8
  - gemfiles/Gemfile-sprockets-3-0
  - gemfiles/Gemfile-sprockets-4-0
  - gemfiles/Gemfile-sprockets-rails-2-2
  - gemfiles/Gemfile-sprockets-rails-master
  - gemfiles/Gemfile-sass-3-1
  - gemfiles/Gemfile-sass-3-2
  - gemfiles/Gemfile-sass-3-3
  - gemfiles/Gemfile-sass-3-4

sudo: false

cache: bundler

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: rbx-2
  exclude:
    - gemfile: gemfiles/Gemfile-sass-3-4
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile-sprockets-4-0
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 1.9.3
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 2.0.0
    - gemfile: gemfiles/Gemfile-rails-5-0
      rvm: 2.1
